### ISSUE TITLE
Service registration crashes when registering generic handlers

### ISSUE THREAD

**Issue by tlycken** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#12]
I want to register a generic handler, `Handler<T>`, that can handle requests of the generic type `Request<T>`, so I tried this:

    public class MediatRConfigTests
    {
        public class Request<T> : IRequest<IReadOnlyCollection<T>> { }

        public class Handler<T> : IAsyncRequestHandler<Request<T>, IReadOnlyCollection<T>>
        {
            public Task<IReadOnlyCollection<T>> Handle(Request<T> message)
            {
                return Task.FromResult(new ReadOnlyCollection<T>(new T[] { }) as IReadOnlyCollection<T>);
            }
        }

        [Fact]
        public void MediatRCanInstantiateGenericHandlers()
        {
            var serviceCollection = new Microsoft.Extensions.DependencyInjection.ServiceCollection();
            serviceCollection.AddMediatR(typeof(Handler<>));
            var serviceProvider = serviceCollection.BuildServiceProvider();
            var mediator = (IMediator)serviceProvider.GetService(typeof(IMediator));
            var result = mediator.Send(new Request<string>()); // an empty IReadOnlyCollection<string>
        }
    }

However, that crashes on `serviceCollection.BuildServiceProvider()`, with an `ArgumentException` stating 

    Cannot instantiate implementation type 'XUnitTestProject1.MediatRConfigTests+Handler`1[T]' for 
    service type 'MediatR.IAsyncRequestHandler`2[XUnitTestProject1.MediatRConfigTests+Request`1[T],System.Collections.Generic.IReadOnlyCollection`1[T]]'.

I wouldn't have been surprised if support for this depended on the IoC container, and this one happened not to support it, but the README explicitly states that this library "supports generic variance of handlers."

Am I doing something weird here, or is this a bug?

**Comment by tlycken** [comment]
As a side note, since it crashes already when building the service provider, an ASP.NET Core app crashes with a really nasty error that doesn't manifest itself in any logs or anything, because it's too early in the pipeline for those things to have been hooked up. The debugger in VS does catch it, though.

**Comment by tlycken** [comment]
Addendum, in case it's relevant - this is in a NetCoreApp1.1 project, with the following nuget packages installed:

```
<ItemGroup>
  <PackageReference Include="MediatR" Version="3.0.1" />
  <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="2.0.0" />
  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="1.1.1" />
  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
  <PackageReference Include="xunit" Version="2.2.0" />
  <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
</ItemGroup>
```

**Comment by tlycken** [comment]
@jbogard Do you have any idea on this?

**Comment by jbogard** [comment]
No not really unfortunately :(

**Comment by tlycken** [comment]
Is my usage according to what's supposed to work? Does the test fail for you too, or is it something weird with my configuration elsewhere?

**Comment by jbogard** [comment]
I wonder, you might try upgrading to netcore2.0?

**Comment by tlycken** [comment]
Same failure when the test project is `netcoreapp2.0`. Should I submit a PR with this test added to the test suite?

**Comment by jbogard** [comment]
I just pushed out a new version, can you try this?

**Comment by tlycken** [comment]
Hm. No, still fails with the same exception on v3.0.0.

```
System.ArgumentException : Cannot instantiate implementation type 'XUnitTestProject1.MediatRConfigTests+Handler`1[T]' for service type 'MediatR.IAsyncRequestHandler`2[XUnitTestProject1.MediatRConfigTests+Request`1[T],System.Collections.Generic.IReadOnlyCollection`1[T]]'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.Populate(IEnumerable`1 descriptors)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory..ctor(IEnumerable`1 descriptors)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services)
   at XUnitTestProject1.MediatRConfigTests.<MediatRCanInstantiateGenericHandlers>d__2.MoveNext() in C:\Users\tomas\Documents\Visual Studio 2017\Projects\XUnitTestProject1\XUnitTestProject1\MediatRGenericHandlers.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

Now that the tool chain is updated I had no problem adding this request/handler pair to the test suite in this project (let me know if you want a PR), with the result that every single test fails (because the setup throws 😄)...

Are we sure this use case is supported in the container? I noticed a skipped test with reference to https://github.com/aspnet/DependencyInjection/issues/471, which might indicate otherwise. (That issue is not the exact same use case, but maybe it's still relevant? I'm not sure enough on the terminology to tell...)

**Comment by murbanowicz** [comment]
Any updates on this?
I am having this issue on .NET Core 2.1.

My Nuget packages:
```
<ItemGroup>
    <PackageReference Include="MediatR" Version="4.0.1" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="4.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-preview1-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.0-preview1-final" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.1.0-preview1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="2.2.0" />
  </ItemGroup>
```

I am using example of eShopOnContainers, Ordering service.
https://github.com/dotnet-architecture/eShopOnContainers/tree/d2f7d6a5d6d9cc90caf9f7c6503bec459115c7af/src/Services/Ordering/Ordering.API/Application/Commands

My app crashes on startup when trying to register IdentifiedCommandHandler:
```
public class IdentifiedCommandHandler<T, R> : IRequestHandler<IdentifiedCommand<T, R>, R>
        where T : IRequest<R>
    {
        private readonly IMediator _mediator;
        private readonly IRequestManager _requestManager;

        public IdentifiedCommandHandler(IMediator mediator, IRequestManager requestManager)
        {
            _mediator = mediator;
            _requestManager = requestManager;
        }

        /// <summary>
        /// Creates the result value to return if a previous request was found
        /// </summary>
        /// <returns></returns>
        protected virtual R CreateResultForDuplicateRequest()
        {
            return default(R);
        }

        /// <summary>
        /// This method handles the command. It just ensures that no other request exists with the same ID, and if this is the case
        /// just enqueues the original inner command.
        /// </summary>
        /// <param name="message">IdentifiedCommand which contains both original command & request ID</param>
        /// <returns>Return value of inner command or default value if request same ID was found</returns>
        public async Task<R> Handle(IdentifiedCommand<T, R> message, CancellationToken cancellationToken)
        {
            var alreadyExists = await _requestManager.ExistAsync(message.Id);
            if (alreadyExists)
            {
                return CreateResultForDuplicateRequest();
            }
            else
            {
                await _requestManager.CreateRequestForCommandAsync<T>(message.Id);

                var result = await _mediator.Send(message.Command);
                
                return result;
            }
        }
    }
```


Error:
```
System.ArgumentException: 'Cannot instantiate implementation type 'MyProject.API.Application.Commands.IdentifierCommandHandler`2[T,R]' for service type 'MediatR.IRequestHandler`2[MyProject.API.Application.Commands.IdentifiedCommand`2[T,R],R]'.'
```

I will appreciate any help on that.

**Comment by tlycken** [comment]
@murbanowicz It's not fully supported by the underlying container, see #13 and https://github.com/aspnet/Home/issues/2341

You can get it working by using eg autofac instead of the default container, but that comes with its own baggage (mostly in terms of more setup and a less obvious relationship between your DI container and the framework).

**Comment by murbanowicz** [comment]
So what can I do to make it working with native DI ?

**Comment by cloversmeh** [comment]
This not possible at the moment.
The only option is to use Extensions:

For example, you must implement the following Handle:

`
public class MyHandler : IRequestHandler<MyQuery, MyResponse> {...}
public class MyHandler<T> : IRequestHandler<MyQuery<T>, MyResponse<T>> {...}
public class MyHandler<T> : IRequestHandler<MyQuery, MyResponse> {...}
public class MyHandler<T> : IRequestHandler<MyQuery<T>, MyResponse<List<T>>> {...}
public class MyHandler<T> : IRequestHandler<MyQuery<T>, MyResponse<object> {...}
public class MyHandler<T> : IRequestHandler<MyQuery<T>, MyResponse<List<object>> {...}
...
`

The following extension will allow you to do this automatically provided that T: ISomeInterface:
I apologize in advance for the code, I'm just learning.


MediatorExtensions.cs:  https://gist.github.com/cloversmeh/a8343400a33e6b069a478d648535eaca
Startup.cs: https://gist.github.com/cloversmeh/3e444f754104691a73b42a2a99236773

**Comment by murbanowicz** [comment]
@cloversmeh are you saying that if I will use this extension, it will work with my IdentifiedCommandHandler?

**Comment by MaciejWierzchowski** [comment]
I'm not sure if I'm missing something, but I don't quite understand how this is not supported by container. If I do this (see example from the first post) everything seem to be working:

```
[Fact]
public void MediatRCanInstantiateGenericHandlers()
{
    var serviceCollection = new Microsoft.Extensions.DependencyInjection.ServiceCollection();
    //serviceCollection.AddMediatR(typeof(Handler<>));
    serviceCollection.AddScoped<ServiceFactory>(p=> type=> p.GetService(type));
    serviceCollection.AddScoped<IMediator, Mediator>();
    serviceCollection.AddTransient<IAsyncRequestHandler<Request<string>, IReadOnlyCollection<string>>, Handler<string>()
    
    var serviceProvider = serviceCollection.BuildServiceProvider();
    var mediator = (IMediator)serviceProvider.GetService(typeof(IMediator));
    var result = mediator.Send(new Request<string>()); // an empty IReadOnlyCollection<string>
}
```

I haven't run the code above, but I have pretty much the same setup as above with IRequestHandler<TRequest, TResponse> and it works. 
Of course if I keep `serviceCollection.AddMediatR(typeof(Handler<>));` things go to hell. 

Isn't there a way to exclude registrations of multi level generics by this package, so that I can register my handlers type by type on my own? I'm ok with having one extra line of code to register all of the `Handler<string>`, `Handler<int>` etc.

**Comment by Caldas** [comment]
So there are no ways to use `INotificationHandler<>` using Asp .Net Core DI @jbogard ?

**Comment by jbogard** [comment]
@Caldas I'm not aware of any limitations?

**Comment by Caldas** [comment]
At https://github.com/jbogard/MediatR/blob/master/samples/MediatR.Examples.AspNetCore/Program.cs I saw 

```
//This causes a type load exception. https://github.com/jbogard/MediatR.Extensions.Microsoft.DependencyInjection/issues/12
//services.AddScoped(typeof(INotificationHandler<>), typeof(ConstrainedPingedHandler<>));
```

**Comment by Caldas** [comment]
At https://github.com/jbogard/MediatR/blob/master/samples/MediatR.Examples.AspNetCore/Program.cs I saw 

```
//This causes a type load exception. https://github.com/jbogard/MediatR.Extensions.Microsoft.DependencyInjection/issues/12
//services.AddScoped(typeof(INotificationHandler<>), typeof(ConstrainedPingedHandler<>));
```

That is not the right way to register *INotificationHandler<>* @jbogard ??

**Comment by vip32** [comment]
any update on the INotificationHandler not being supported in netcore DI?

**Comment by jbogard** [comment]
@Caldas it is for open generic handlers. My scanning here finds closed and concrete open types:

`PingedHandler : INotificationHandler<Pinged>`
`AllHandlers<TNotification> : INotificationHandler<TNotification>`

Registration needs both the closed and open types.
