### ISSUE TITLE
Support for MediatR 5.0.0?

### ISSUE THREAD

**Issue by tlycken** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#27]
I have a very simple setup with ASP.NET Core DI, and the latest versions of MediatR and this package, and I'm getting

> Application startup exception: System.TypeLoadException: Could not load type 'MediatR.SingleInstanceFactory' from assembly 'MediatR, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'.

I'm literally only doing

```
services.AddMediatR(typeof(ARequestHandlerInADifferentProject));
```

to make this happen. But looking at the source tree for MediatR, it seems that the `SingleInstanceFactory` doesn't exist anymore (so it's not so strange that this package can't find it). Does this package need an update to work with 5.0?

Can I help?

**Comment by tlycken** [comment]
By diving a little deeper, I found that installing version `5.0.1-alpha-0002` of both MediatR and this package resolves the issue. Any idea when a compatible pair of non-prerelease versions of the two packages will be pushed?

**Comment by aredfox** [comment]
Same issue here, :/

**Comment by jbogard** [comment]
This week!

**Comment by Andrew-Brad** [comment]
I get a similar TypeLoaderException, except mine is unique in that it only occurs for unit tests (XUnit).

 System.AggregateException : One or more errors occurred. (Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.) (The following constructor parameters did not have matching fixture data: SharedTestServerFixture fixture)
---- System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
---- The following constructor parameters did not have matching fixture data: SharedTestServerFixture fixture
![typeloaderexception](https://user-images.githubusercontent.com/4649211/40336511-9fb8be5e-5d2f-11e8-884c-42df9e9dcbac.PNG)


Cloneable repro: https://github.com/Andrew-Brad/ApiKickstart/tree/ef-core-2

The TypeLoaderException is specifically for an EF Relational package.
Also attached a screenshot of what VS is showing.  Tried the alpha 002 packages with no changes.  App runs fine with F5, only the unit test project seemed to uncover this.

**Comment by Andrew-Brad** [comment]
Played around with it a bit more...looks like the reflection issue was resolved by passing the Startup assembly into the AddMediatr() overload.

`services.AddMediatR(typeof(Startup).Assembly);`

**Comment by eestein** [comment]
Still happened with me on 5.0.1, had to downgrade to 4.1.0 :/

**Comment by jbogard** [comment]
Releasing today!

**Comment by dkosasih** [comment]
Hello,
I still have the same issue on 5.0.1 and 5.1.0

**Comment by RHartnessCM** [comment]
FYI, this is still broken for 5.0.1.0 and 5.1.0.0.  I ended up downgrading to 3.0.1.0 because we have a few other, unrelated projects in our code base that are 3.0.  This fixed my issues in my new project that's being setup to use use MediatR.  If possibly, however, I would like to upgrade to the most current, stable version of MediatR.

**Comment by jbogard** [comment]
Just pushed 5.1.0 of both packages. If you're receiving this error again, please open a new issue.

**Comment by jbogard** [comment]
What is broken?

**Comment by thenewbieprogrammer** [comment]
When adding MediatR in Startup.CS:
" services.AddMediatR();"
"services.AddMediatR(typeof(Startup));"
"  services.AddMediatR(typeof(Startup).Assembly); "

Then Exception User-Unhandled:
System.TypeLoadException: 'Could not load type 'MediatR.SingleInstanceFactory' from assembly 'MediatR, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null'.'


Details:

System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'MediatR.SingleInstanceFactory' from assembly 'MediatR,

**Comment by thenewbieprogrammer** [comment]
This was my fix: 
1) Open Package Manager Console
2) Install-Package MediatR.Extensions.Microsoft.DependencyInjection

**Comment by nathanchere** [comment]
Surprised no-one (including @jbogard ) has mentioned this yet.
It's explained in the migration guide:
https://github.com/jbogard/MediatR/wiki/Migration-Guide-4.x-to-5.0

Particular:

```
Migrating registration
With the two delegates collapsed into one, for most containers you can remove the MultiInstanceFactory registration, and rename the SingleInstanceFactory registration to ServiceFactory.

Some of the older containers cannot automatically handler IEnumerable<T>, check the samples folder where all of the registrations now reflect the new single delegate.
```

Sometimes it pays to RTFM.
